apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pimcore.fullname" . }}-phpfpm-conf
  labels:
        {{- include "pimcore.labels" . | nindent 4 }}
data:
  php-config.conf: |
    [global]
    include=etc/php-fpm.d/*.conf
