apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pimcore.fullname" . }}-migrate
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-failed,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/name: {{ include "pimcore.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-migrate
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pimcore.serviceAccountName" . }}
      restartPolicy: Never
      initContainers:
        - name: "wait-for-mysql"
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nslookup {{ .Values.pimcore.db.host }}; do echo waiting for mysql; sleep 2; done;']
          securityContext:
            privileged: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageCredentials.registry }}/php:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "pimcore.fullname" . }}-dotenv
          command: ["/bin/sh", "-c"]
          args:
            - >
              ./bin/console doctrine:migrations:migrate --no-interaction &&
              ./bin/console assets:install
          volumeMounts:
            - name: php-ini
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: php-config
              mountPath: /usr/local/etc/php-fpm.conf
              subPath: php-config.conf
            - name: php-pool-config
              mountPath: /usr/local/etc/php-fpm.d/zz-www.conf
              subPath: php-pool-config.conf
            {{- range .Values.pimcore.sharedFolders }}
            - name: pimcore-data
              mountPath: /var/www/pimcore/{{ . }}
              subPath: {{ . }}
            {{- end }}
      volumes:
      - name: pimcore-data
        persistentVolumeClaim:
          claimName: pimcore-data
      - name: php-ini
        configMap:
          name: {{ template "pimcore.fullname" . }}-phpfpm-ini
      - name: php-config
        configMap:
          name: {{ template "pimcore.fullname" . }}-phpfpm-conf
      - name: php-pool-config
        configMap:
          name: {{ template "pimcore.fullname" . }}-phpfpm-pool-conf
