settings:
  kubeContext: "minikube"
  globalMaxHistory: 5

helmRepos:
  bitnami: "https://charts.bitnami.com/bitnami"
  nginx: "https://kubernetes.github.io/ingress-nginx"


namespaces:
  pimcore:
    protected: false

apps:
  mysql:
    namespace: "pimcore"
    enabled: true
    chart: "bitnami/mariadb"
    version: 7.10.3
    valuesFile: "./mysql/values.yaml"
    priority: -1

  redis:
    namespace: "pimcore"
    enabled: true
    enabled: true
    chart: "bitnami/mariadb"
    version: 11.1.1
    valuesFile: "./redis/values.yaml"
    priority: -1

  nginx-ingress:
    namespace: "pimcore"
    enabled: true
    chart: "nginx/nginx-ingress"
    version: 0.6.1

  pimcore:
    namespace: "pimcore"
    enabled: true
    chart: "./pimcore"
    version: 0.1.0
    valuesFile: "./pimcore/values.yaml"
